### ISSUE TITLE
Fine to use with other projects?

### ISSUE THREAD

**Issue by ioolkos** [Pondidum/Nomad-RabbitMQ-Demo#1]
Hi, thanks for your blog post and templates here. Is this fine to use as a starting template for other projects? (no license visible).
Or would you recommend other templates? (I'm new to Nomad)

**Comment by Pondidum** [comment]
Hi!

It should be fine to use as a basis for your own setup - and I'll add a permissive license shortly (something like BSD).

**Comment by ioolkos** [comment]
That's great, thanks!
